# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3-jdk-11

pipelines:
  pull-requests:
    '**':
      - parallel:
          - step:
              name: Test
              caches:
                - maven
              script:
                - mvn verify --file pom.xml
              after-script:
                # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
                - pipe: atlassian/checkstyle-report:0.2.0
          - step:
              name: Security Scan
              script:
                # Run a security scan for sensitive data.
                # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
                - pipe: atlassian/git-secrets-scan:0.4.3